#!/bin/bash

export venv=$OPENSHIFT_DATA_DIR/venv

if [ -d $venv ] ; then
    echo "Not rebuilding virtualenv."
else
    virtualenv $venv
fi

source $venv/bin/activate
python $OPENSHIFT_REPO_DIR/setup.py develop
