#!/bin/bash

export venv=$OPENSHIFT_DATA_DIR/venv

if [ ! -d $venv ] ; then
    virtualenv $venv
fi

# make egg cache writable
export PYTHON_EGG_CACHE=$OPENSHIFT_DATA_DIR/eggcache
if [ ! -d $PYTHON_EGG_CACHE ] ; then
    mkdir $PYTHON_EGG_CACHE
fi

source $venv/bin/activate
python $OPENSHIFT_REPO_DIR/setup.py develop
