#!/bin/bash

export venv=$OPENSHIFT_DATA_DIR/venv

if [ -d $venv ] ; then
    echo "Not rebuilding virtualenv."
else
    virtualenv $venv
    source $venv/bin/activate
fi

$venv/bin/python $OPENSHIFT_REPO_DIR/setup.py develop
